FROM daocloud.io/library/ubuntu:14.04.1
MAINTAINER mango "1192297699@qq.com"  
RUN cd /opt
RUN mkdir /opt/jdk
RUN apt-get update -y
RUN apt-get install wget -y
RUN apt-get install -y python-software-properties software-properties-common


RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer


# 配置无秘钥安装

# 1. 安装 OpenSSH, OpenSSL, bzip2-devel
# 2. 同时配置SSH免密钥登陆
RUN apt-get install -y openssh-server openssh-client openssl && \
    apt-get clean all && \
    ssh-keygen -t rsa -f ~/.ssh/id_rsa -P '' && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    
ADD config/ssh/ssh_config /root/.ssh/config
RUN chmod 600 /root/.ssh/config && \
    chown root:root /root/.ssh/config
  
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV PATH=$PATH:$JAVA_HOME/bin:.

CMD ["/bin/bash"]